server:
  port: 9014
spring:
  application:
    name: article-crawler #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/article-crawler?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: MYSQL
    show-sql: true
#自定义Redis属性
redis:
  host: 127.0.0.1
file:
  savepath: E:\data\images
logging:
  level:
    com:
      tensquare:
        articlecrawler: debug
    org.springframework: debug